name: number_trivia
description: An app for Number Trivia API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.1
  dio: ^3.0.9
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  hive_generator: ^0.7.1
  dartz: ^0.9.1
  cupertino_icons: ^0.1.3
  get_it: ^4.0.4
  data_connection_checker: ^0.3.4
  path_provider: ^1.6.11
  firebase_crashlytics: ^0.1.4+1
  firebase_remote_config: ^0.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mockito: ^4.1.1

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

